FROM python:3.11-slim

WORKDIR /app

COPY requirements.api.txt .
RUN pip install --no-cache-dir -r requirements.api.txt

COPY api ./api

RUN mkdir -p /app/reference

EXPOSE 8000

CMD ["uvicorn", "api.serving_api:app", "--host", "0.0.0.0", "--port", "8000"]
