FROM python:3.11-slim

WORKDIR /app

COPY requirements.pipeline.txt .
RUN pip install --no-cache-dir -r requirements.pipeline.txt

COPY scripts ./scripts
COPY reference ./reference

RUN mkdir -p /app/data

CMD ["sh", "-c", "python -m scripts.taxi_job && python -m scripts.rainfall_job"]
